#!/bin/bash

# ============================================================================
# step02_fmriprep_v2.sh
# Created by Mario Murakami
#
# STEP 2 V2 — Two-part script:
#
#   PART 1  Subject list name correction  (previously step03)
#           Reads utility/SubjectList.txt and converts each raw ID to BIDS
#           format, writing the result to utility/SubjectListBIDS.txt.
#           Conversion rule:
#             7T1019HC_042726  →  sub-7T1019HC042726
#           (prepend 'sub-' and remove all underscores)
#
#   PART 2  fMRIPrep (local, sequential)   (previously step14/step02)
#           Runs fMRIPrep via Singularity for each BIDS subject in
#           utility/SubjectListBIDS.txt, one subject at a time.
#
# Usage:
#   bash step02_fmriprep_v2.sh
#   bash step02_fmriprep_v2.sh /path/to/CustomSubjectList.txt
#
# NOTE: Must run on the cluster — requires Singularity and /autofs mounts.
# ============================================================================

# ── Environment ───────────────────────────────────────────────────────────────
# Resolve the directory this script lives in (works even when called from
# a different working directory).
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Source the fMRIPrep environment: sets up Singularity, FreeSurfer, FSL,
# AFNI, conda, and other cluster-side dependencies.
source "${SCRIPT_DIR}/utility/fmriprep_env.sh"

echo "============================================"
echo " Created by Mario Murakami"
echo " STEP 2 V2 — Name correction + fMRIPrep"
echo " Date: $(date)"
echo "============================================"

# ── Paths — edit these for a new project ─────────────────────────────────────

# Raw subject ID list passed as first argument; defaults to utility/SubjectList.txt
# (subject lists live in the utility/ folder).
raw_subj_list=${1:-"${SCRIPT_DIR}/utility/SubjectList.txt"}

# Output file: BIDS-format subject IDs (generated by Part 1, consumed by Part 2)
bids_subj_list="${SCRIPT_DIR}/utility/SubjectListBIDS.txt"

# BIDS sourcedata root — the output directory from step01 (heudiconv)
bids_dir=/autofs/cluster/vagabond/USERS/MARIO/Projects/lyme/sourcedata

# fMRIPrep derivatives output folder
derivatives_dir=${bids_dir}/derivatives/fmriprep

# FreeSurfer subjects directory (recon-all outputs live here)
fs_dir=${bids_dir}/derivatives/freesurfer

# fMRIPrep working directory — stores intermediate files; can be very large
work_dir=/autofs/cluster/vagabond/USERS/MARIO/Projects/lyme/codes/working-fmriprep

# Singularity image for fMRIPrep (pin the version here for reproducibility)
fmriprep_simg=/autofs/cluster/vagabond/USERS/MARIO/Pipelines/my_images/fmriprep-25.2.3.simg

# FreeSurfer license file
fs_license=/autofs/cluster/vagabond/USERS/MARIO/Pipelines/license.txt

echo ""
echo " Raw subject list:  ${raw_subj_list}"
echo " BIDS subject list: ${bids_subj_list}"
echo " BIDS dir:          ${bids_dir}"
echo " Derivatives:       ${derivatives_dir}"
echo ""

# ── PART 1: Convert raw IDs → BIDS format ────────────────────────────────────
# Each line of SubjectList.txt is a raw scanner ID like 7T1019HC_042726.
# BIDS requires subject labels of the form sub-<label> with no underscores
# in the label portion.  This loop applies:
#   1. Remove all underscores from the raw ID   (bash parameter expansion //_/)
#   2. Prepend 'sub-'
echo "============================================"
echo " PART 1: Generating BIDS subject list"
echo "============================================"

# Verify the raw subject list exists before proceeding
if [ ! -f "${raw_subj_list}" ]; then
    echo "ERROR: Subject list not found: ${raw_subj_list}"
    exit 1
fi

# Truncate/create the output file (> redirects nothing, just opens the file)
> "${bids_subj_list}"

while IFS= read -r line; do
    # Skip blank lines
    [ -z "${line}" ] && continue

    # Apply the BIDS ID transformation
    bids_id="sub-${line//_/}"

    echo "${bids_id}" >> "${bids_subj_list}"
    echo "  ${line}  →  ${bids_id}"
done < "${raw_subj_list}"

# Count how many subjects were written
n_subjects=$(grep -c . "${bids_subj_list}")
echo ""
echo " Saved ${n_subjects} subject(s) to: ${bids_subj_list}"

# ── PART 1.5: BIDS Validator ──────────────────────────────────────────────────
# Validates the BIDS structure of sourcedata before running fMRIPrep.
# If bids-validator is not found the step is skipped with a warning (not fatal).
# Install with: npm install -g bids-validator
echo ""
echo "============================================"
echo " PART 1.5: BIDS Validator"
echo "============================================"

if command -v bids-validator &>/dev/null; then
    echo " Running: bids-validator ${bids_dir}"
    bids-validator "${bids_dir}"
    bids_exit=$?
    if [ ${bids_exit} -eq 0 ]; then
        echo " BIDS validation passed ✓"
    else
        echo " BIDS validation reported issues — review output above before continuing."
        echo " (Proceeding anyway; fix critical errors before submitting to a journal.)"
    fi
elif command -v npx &>/dev/null; then
    echo " Running: npx bids-validator ${bids_dir}"
    npx bids-validator "${bids_dir}"
else
    echo " WARNING: bids-validator not found in PATH."
    echo "   Install: npm install -g bids-validator"
    echo "   Skipping validation — continuing to fMRIPrep."
fi

# ── PART 2: Run fMRIPrep locally via Singularity ─────────────────────────────
# Loops over every BIDS subject in utility/SubjectListBIDS.txt and runs fMRIPrep
# sequentially (one subject at a time).
#
# What fMRIPrep does per subject:
#   - T1w brain extraction and bias field correction (ANTs)
#   - FreeSurfer surface reconstruction (recon-all)
#   - BOLD slice-timing correction (skipped here via --ignore slicetiming;
#     handled upstream by RETROICOR)
#   - Head motion estimation and correction
#   - Susceptibility distortion correction (requires fieldmaps in BIDS)
#   - Spatial normalisation: native T1w + MNI152NLin2009cAsym
#   - BOLD confound table: motion params, aCompCor, FD, DVARS, global signal
#   - CIFTI dense timeseries output (--cifti-output)
echo ""
echo "============================================"
echo " PART 2: Running fMRIPrep"
echo "============================================"

# Create output directories — fMRIPrep will fail if these don't exist
mkdir -p "${derivatives_dir}"
mkdir -p "${fs_dir}"
mkdir -p "${work_dir}"

while IFS= read -r subject; do
    # Skip blank lines
    [ -z "${subject}" ] && continue

    echo ""
    echo "--------------------------------------------"
    echo " Subject : ${subject}"
    echo " Started : $(date)"
    echo "--------------------------------------------"

    # Run fMRIPrep inside the Singularity container.
    #
    # -B flags bind-mount cluster paths into the container so Singularity
    # can see them.  The specific project directories are mounted explicitly
    # (in addition to the top-level cluster mounts) to ensure the container
    # can write to derivatives/ and working/.
    #
    # Key flags:
    #   --participant-label   the full BIDS subject ID (e.g. sub-7T1019HC042726)
    #   --output-spaces       write outputs in native T1w + MNI152 space
    #   --fs-subjects-dir     where recon-all outputs are stored/resumed
    #   --work-dir            intermediate files (delete after QC to save disk)
    #   --cifti-output        also write HCP-style grayordinate CIFTI files
    #   --ignore slicetiming  skip fMRIPrep's internal STC (handled by RETROICOR)
    #   --skip-bids-validation  skip validator (avoids issues with partial datasets)
    #   --mem_mb              memory ceiling passed to fMRIPrep's workflow engine
    singularity run --cleanenv \
        -B /autofs \
        -B /usr/pubsw \
        -B /cluster \
        -B /homes \
        -B /space \
        -B /vast \
        -B /run/user \
        -B /autofs/cluster/vagabond/USERS/MARIO/Pipelines \
        -B /autofs/cluster/vagabond/USERS/MARIO/Pipelines/my_images \
        -B /autofs/cluster/vagabond/USERS/MARIO/Projects/lyme \
        -B /autofs/cluster/vagabond/USERS/MARIO/Projects/lyme/codes \
        -B /autofs/cluster/vagabond/USERS/MARIO/Projects/lyme/sourcedata \
        -B /autofs/cluster/vagabond/USERS/MARIO/Projects/lyme/sourcedata/derivatives \
        -B /autofs/cluster/vagabond/USERS/MARIO/Projects/lyme/codes/working-fmriprep \
        "${fmriprep_simg}" \
        "${bids_dir}" "${derivatives_dir}" participant \
        --participant-label "${subject}" \
        --output-spaces T1w MNI152NLin2009cAsym \
        --fs-subjects-dir "${fs_dir}" \
        --work-dir "${work_dir}" \
        --cifti-output \
        --fs-license-file "${fs_license}" \
        --ignore slicetiming \
        --skip-bids-validation \
        --mem_mb 50000

    # Check the exit code of singularity and report per-subject status
    fp_exit=$?
    if [ ${fp_exit} -eq 0 ]; then
        echo ""
        echo " ✓ Done: ${subject}  ($(date))"
    else
        echo ""
        echo " ✗ FAILED: ${subject}  ($(date))"
        echo "   Check logs in: ${work_dir}"
        continue
    fi

    # ── Step 13: pre vs post fMRIPrep visual QC (one GIF per BOLD run) ───────
    # Compares each raw BIDS BOLD (pre) against fMRIPrep's preprocessed output
    # (post) and saves an animated side-by-side GIF for quick QC.
    # Note: after RETROICOR, re-run this step pointing to the RETROICOR-corrected
    # files to visualise the physiological noise removal.
    echo ""
    echo "  [Step 13] Generating pre/post QC GIFs for ${subject} ..."

    # Python interpreter to use (activates same env the GUI uses)
    PYTHON="${SCRIPT_DIR}/../../physioparse/gui/../../../anaconda3/envs/Neuroimaging/bin/python3"
    if [ ! -x "${PYTHON}" ]; then
        PYTHON="python3"   # fallback to system python3
    fi

    step13_script="${SCRIPT_DIR}/step13_preproc_optional_check_pre-post.py"

    # Determine the subject label without 'sub-' prefix for BIDS func path
    subj_label="${subject#sub-}"

    # Raw BIDS func dir for this subject
    raw_func_dir="${bids_dir}/${subject}/ses-01/func"

    # fMRIPrep preprocessed func dir for this subject
    fp_func_dir="${derivatives_dir}/${subject}/ses-01/func"

    # QC output dir — stored alongside fMRIPrep HTML reports
    qc_dir="${derivatives_dir}/${subject}/figures"
    mkdir -p "${qc_dir}"

    # Loop over every BIDS BOLD run for this subject
    for raw_bold in "${raw_func_dir}"/*_bold.nii.gz; do
        [ -f "${raw_bold}" ] || continue

        # Build the expected fMRIPrep output filename for this run (T1w space)
        boldbase=$(basename "${raw_bold}" _bold.nii.gz)
        fp_bold="${fp_func_dir}/${boldbase}_space-T1w_desc-preproc_bold.nii.gz"

        if [ ! -f "${fp_bold}" ]; then
            echo "  [Step 13] fMRIPrep output not found, skipping: $(basename ${fp_bold})"
            continue
        fi

        gif_out="${qc_dir}/${boldbase}_prepost_fmriprep.gif"

        echo "  [Step 13]  $(basename ${raw_bold})  →  $(basename ${gif_out})"
        "${PYTHON}" "${step13_script}" \
            "${raw_bold}" "${fp_bold}" \
            -o "${gif_out}" \
            --plane axial \
            --fps 10 \
            --step 2

        if [ $? -eq 0 ]; then
            echo "  [Step 13] ✓ GIF written: ${gif_out}"
        else
            echo "  [Step 13] ✗ GIF generation failed for ${boldbase}"
        fi
    done

done < "${bids_subj_list}"

echo ""
echo "============================================"
echo " All subjects processed.  $(date)"
echo "============================================"

# ── PART 3: QC — Mean Framewise Displacement + registration check ─────────────
# Reads the fMRIPrep confounds TSVs and reports mean FD per subject.
# Subjects with mean FD > 0.9 mm are flagged.  Also checks whether MNI-space
# BOLD outputs exist (basic registration sanity check).
# Output: a JSON log at <derivatives_dir>/qc_fd_summary.json
echo ""
echo "============================================"
echo " PART 3: QC — FD + registration check"
echo "============================================"

python3 - "${derivatives_dir}" "${bids_subj_list}" <<'PYEOF'
import sys, csv, json, pathlib, datetime

deriv      = pathlib.Path(sys.argv[1])
subj_file  = pathlib.Path(sys.argv[2])
FD_THRESH  = 0.9  # mm — flag subjects above this mean FD

subjects = [l.strip() for l in subj_file.read_text().splitlines() if l.strip()]
results  = {}

for subj in subjects:
    func_dir = deriv / subj / "func"
    entry = {"has_output": func_dir.is_dir(), "mean_fd": None,
             "flagged_fd": False, "has_mni_bold": False}

    if not entry["has_output"]:
        print(f"  {subj}: no fMRIPrep output directory")
        results[subj] = entry
        continue

    # MNI BOLD check
    mni_bolds = list(func_dir.glob("*MNI152*desc-preproc_bold.nii.gz"))
    entry["has_mni_bold"] = len(mni_bolds) > 0
    if not entry["has_mni_bold"]:
        print(f"  {subj}: ⚠  MNI-space BOLD not found — check registration")

    # FD from confounds TSV
    fds = []
    for tsv in func_dir.glob("*_desc-confounds_timeseries.tsv"):
        with open(tsv) as f:
            for row in csv.DictReader(f, delimiter="\t"):
                v = row.get("framewise_displacement", "n/a")
                if v not in ("n/a", "", "NA"):
                    try:
                        fds.append(float(v))
                    except ValueError:
                        pass

    if fds:
        mfd = sum(fds) / len(fds)
        entry["mean_fd"]     = round(mfd, 4)
        entry["flagged_fd"]  = mfd > FD_THRESH
        flag_str = f"  ⚠ FLAGGED (>{FD_THRESH} mm)" if mfd > FD_THRESH else "  ✓"
        print(f"  {subj}: mean FD = {mfd:.4f} mm{flag_str}")
    else:
        print(f"  {subj}: confounds TSV not found — FD unavailable")

    results[subj] = entry

# Write JSON log
log_path = deriv / "qc_fd_summary.json"
payload = {
    "generated":  datetime.datetime.now().isoformat(timespec="seconds"),
    "fd_threshold_mm": FD_THRESH,
    "results": results,
}
log_path.write_text(json.dumps(payload, indent=2))
print(f"\n QC log written: {log_path}")
n_flagged = sum(1 for v in results.values() if v.get("flagged_fd"))
n_noreg   = sum(1 for v in results.values() if not v.get("has_mni_bold"))
print(f" Subjects flagged (FD > {FD_THRESH}mm): {n_flagged}/{len(results)}")
if n_noreg:
    print(f" Subjects missing MNI BOLD: {n_noreg}/{len(results)}  ← check registration")
PYEOF
